NAME =	animals
SRC =	Dog.cpp Cat.cpp Brain.cpp Animal.cpp main.cpp
HPP = Animal.hpp Dog.hpp Cat.hpp Brain.hpp

CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98 -I.

all: $(NAME)

$(NAME): $(SRC) $(HPP)
	$(CXX) $(CXXFLAGS) -o $(NAME) $(SRC)

clean:
	rm -f $(NAME)

fclean: clean

re: fclean all

.PHONY: all clean fclean re
